#!/system/bin/sh
# detect.sh - Probe a rooted Android device for external-USB-Wi-Fi buildability.
#
# Reads the running kernel, checks whether its source commit is publicly
# buildable, inspects the kernel config, finds a plugged-in USB Wi-Fi adapter,
# and flags known blockers (module signing, SELinux, Unisoc watchdog). Emits a
# device-profile.txt you paste into the GitHub Actions build.
#
# It changes NOTHING on the device. Run it as root:
#   su
#   sh detect.sh
#
# Requires: curl with network access (Termux: pkg install curl).

OUT=./device-profile.txt
say() { echo "$*"; }
kv()  { printf '%-22s %s\n' "$1" "$2"; }

need_root() { [ "$(id -u)" = "0" ] && return 0; echo "Run as root (su)."; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

# curl often lives only in Termux, not in the root PATH - add it
for p in /data/data/com.termux/files/usr/bin /system/bin /system/xbin; do
  case ":$PATH:" in *":$p:"*) ;; *) [ -d "$p" ] && PATH="$PATH:$p";; esac
done
export PATH
CURL=""
have curl && CURL=curl
[ -z "$CURL" ] && [ -x /data/data/com.termux/files/usr/bin/curl ] && CURL=/data/data/com.termux/files/usr/bin/curl

need_root
: > "$OUT"

say "=== p30t-mt76 device probe ==="
say ""

# ---------------------------------------------------------------- kernel
KREL="$(uname -r)"
KVER="$(printf '%s' "$KREL" | cut -d- -f1)"      # e.g. 5.15.178
# short git hash is the gXXXXXXXX token in uname -r
KHASH="$(printf '%s' "$KREL" | tr '-' '\n' | grep -E '^g[0-9a-f]{7,}$' | head -1 | sed 's/^g//')"
# android branch token, e.g. android13
KBRANCH="$(printf '%s' "$KREL" | tr '-' '\n' | grep -E '^android[0-9]+$' | head -1)"
KGEN="${KBRANCH}-${KVER%.*}.${KVER##*.}"          # rough; refined below

kv "kernel_release" "$KREL"
kv "kernel_version" "$KVER"
kv "commit_short"   "${KHASH:-<none found>}"
kv "android_branch" "${KBRANCH:-<unknown>}"

# guess the ACK branch (android13-5.15 style)
MAJMIN="$(printf '%s' "$KVER" | cut -d. -f1,2)"   # 5.15
ACK_BRANCH="${KBRANCH:-android13}-${MAJMIN}"
kv "ack_branch_guess" "$ACK_BRANCH"

{
  echo "# device-profile.txt - generated by detect.sh"
  echo "KERNEL_RELEASE=$KREL"
  echo "KERNEL_VERSION=$KVER"
  echo "COMMIT_SHORT=${KHASH}"
  echo "ANDROID_BRANCH=${KBRANCH}"
  echo "ACK_BRANCH_GUESS=${ACK_BRANCH}"
} >> "$OUT"

say ""

# ---------------------------------------------------------- commit public?
COMMIT_OK=no
FULLHASH=""
if [ -n "$KHASH" ] && [ -n "$CURL" ]; then
  say "Checking whether the kernel commit is public on ACK..."
  # gitiles accepts the short hash; a 200 means it exists in kernel/common
  CODE="$($CURL -s -o /dev/null -w '%{http_code}' \
     "https://android.googlesource.com/kernel/common/+/$KHASH" 2>/dev/null)"
  if [ "$CODE" = "200" ]; then
    COMMIT_OK=yes
    kv "commit_public" "YES (HTTP 200) - buildable from this commit"
  else
    kv "commit_public" "NO (HTTP $CODE) - see notes below"
  fi
else
  kv "commit_public" "SKIPPED (no curl or no hash)"
fi
echo "COMMIT_PUBLIC=$COMMIT_OK" >> "$OUT"
say ""

# --------------------------------------------------------------- config
CFG=/proc/config.gz
getcfg() { zcat "$CFG" 2>/dev/null | grep -E "^$1=" | head -1; }
has_y()  { zcat "$CFG" 2>/dev/null | grep -qE "^$1=y"; }

if zcat "$CFG" >/dev/null 2>&1; then
  MODVER=$(has_y CONFIG_MODVERSIONS && echo y || echo n)
  BTF=$(has_y CONFIG_DEBUG_INFO_BTF && echo y || echo n)
  LTOFULL=$(has_y CONFIG_LTO_CLANG_FULL && echo y || echo n)
  LTOTHIN=$(has_y CONFIG_LTO_CLANG_THIN && echo y || echo n)
  MODULES=$(has_y CONFIG_MODULES && echo y || echo n)
  SIG=$(has_y CONFIG_MODULE_SIG_FORCE && echo y || echo n)
  kv "CONFIG_MODULES"        "$MODULES"
  kv "CONFIG_MODVERSIONS"    "$MODVER"
  kv "CONFIG_DEBUG_INFO_BTF" "$BTF"
  kv "LTO_CLANG_FULL/THIN"   "$LTOFULL / $LTOTHIN"
  kv "MODULE_SIG_FORCE"      "$SIG"
  {
    echo "CONFIG_MODULES=$MODULES"
    echo "CONFIG_MODVERSIONS=$MODVER"
    echo "CONFIG_DEBUG_INFO_BTF=$BTF"
    echo "LTO_FULL=$LTOFULL"
    echo "LTO_THIN=$LTOTHIN"
    echo "MODULE_SIG_FORCE=$SIG"
  } >> "$OUT"
else
  kv "config.gz" "NOT READABLE - cannot verify BTF/LTO (build may mismatch)"
  echo "CONFIG_READABLE=no" >> "$OUT"
  MODULES=?; MODVER=?; BTF=?; LTOFULL=?; SIG=?
fi
say ""

# ------------------------------------------------------------ USB adapter
# Known USB IDs -> module + firmware hints
usb_hint() {
  case "$1" in
    0e8d:7612) echo "mt76x2u|mt7662.bin,mt7662_rom_patch.bin|MT7612U (ALFA AWUS036ACM)";;
    0e8d:7610) echo "mt76x0u|mt7610*.bin|MT7610U";;
    0bda:8812) echo "rtl88XXau(vendor)|none(in-driver)|RTL8812AU (needs out-of-tree driver)";;
    0bda:8813) echo "rtl88XXau(vendor)|none(in-driver)|RTL8813AU";;
    148f:5370) echo "rt2800usb|none|RT5370";;
    0cf3:9271) echo "ath9k_htc|htc_9271.fw|AR9271 (ALFA AWUS036NHA)";;
    0846:9030) echo "ath9k_htc|htc_9271.fw|AR9271 (Netgear WNA1100)";;
    *) echo "unknown|unknown|unrecognized - look it up";;
  esac
}

FOUND=""
for d in /sys/bus/usb/devices/*/idProduct; do
  dir=$(dirname "$d"); [ -f "$dir/idVendor" ] || continue
  id="$(cat "$dir/idVendor"):$(cat "$d")"
  # skip hubs/root
  cls=$(cat "$dir/bDeviceClass" 2>/dev/null)
  [ "$cls" = "09" ] && continue
  hint=$(usb_hint "$id")
  drv=$(printf '%s' "$hint" | cut -d'|' -f1)
  fw=$(printf '%s'  "$hint" | cut -d'|' -f2)
  desc=$(printf '%s' "$hint" | cut -d'|' -f3)
  # only report likely wifi (known ids, or has a wireless-ish interface)
  case "$id" in
    0e8d:*|0bda:*|148f:*|0cf3:*|0846:*)
      FOUND="$id"
      kv "usb_wifi_found" "$id at $(basename "$dir")"
      kv "  chipset"      "$desc"
      kv "  driver"       "$drv"
      kv "  firmware"     "$fw"
      {
        echo "USB_ID=$id"
        echo "USB_PATH=$(basename "$dir")"
        echo "DRIVER=$drv"
        echo "FIRMWARE=$fw"
        echo "CHIPSET=$desc"
      } >> "$OUT"
      ;;
  esac
done
[ -z "$FOUND" ] && { kv "usb_wifi_found" "none (plug the adapter in and re-run)"; echo "USB_ID=" >> "$OUT"; }
say ""

# ---------------------------------------------------------- environment
SEL=$(getenforce 2>/dev/null || echo unknown)
kv "selinux" "$SEL"
echo "SELINUX=$SEL" >> "$OUT"

WD=no
lsmod 2>/dev/null | grep -qi native_hang_monitor && WD=yes
kv "unisoc_watchdog" "$WD  (native_hang_monitor; needs autoprobe-off load trick)"
echo "UNISOC_WATCHDOG=$WD" >> "$OUT"

# is this the known-good reference platform?
REF=no
printf '%s' "$KREL" | grep -q "g4ea0fcb5d130" && REF=yes
kv "known_good_ums9230" "$REF"
echo "KNOWN_GOOD_UMS9230=$REF" >> "$OUT"
say ""

# ------------------------------------------------------------- verdict
say "=== VERDICT ==="
BLOCK=0
[ "$MODULES" = "n" ] && { say "BLOCKER: CONFIG_MODULES=n - kernel can't load modules at all."; BLOCK=1; }
[ "$SIG" = "y" ]     && { say "BLOCKER: MODULE_SIG_FORCE=y - unsigned modules will be rejected."; BLOCK=1; }
if [ "$REF" = "yes" ] && [ "$COMMIT_OK" != "yes" ]; then
  COMMIT_OK=yes   # known-good reference: commit is public (verified 4ea0fcb5d130)
fi
[ "$COMMIT_OK" = "no" ] && [ -n "$KHASH" ] && say "WARNING: kernel commit not confirmed public - if the build's module_layout CRC differs from yours, you must locate matching source (vendor GPL drop)."
[ -z "$KHASH" ] && say "WARNING: no git hash in uname -r - hard to match ACK source."
[ "$MODVER" = "y" ] && say "NOTE: MODVERSIONS=y - modules MUST be built from the exact commit (this is normal for GKI)."
[ "$BTF" = "y" ] && say "NOTE: BTF=y - build must keep BTF enabled (workflow installs pahole)."
[ "$LTOTHIN" = "y" ] && say "NOTE: thin LTO in use - set LTO thin in the workflow to match."

if [ "$REF" = "yes" ]; then
  say ""
  say "FAST PATH: this is the known-good UMS9230/T615 reference kernel."
  say "You can use the default workflow inputs as-is."
elif [ "$BLOCK" = "0" ]; then
  say ""
  say "LIKELY BUILDABLE (best-effort). Use device-profile.txt values as workflow inputs."
else
  say ""
  say "NOT BUILDABLE as-is (see BLOCKER lines above)."
fi

say ""
say "Wrote $OUT - paste its values into the GitHub Actions 'Run workflow' inputs."
